name: Keep Alive
on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # Allow manual trigger
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -f ${{ secrets.APP_BASE_URL }}/health | jq || echo "Health check failed but continuing..."
